module.exports = [
  {
    id: 1,
    icon: 'laptop',
    name: 'Customer Flow',
    router: '/dashboard',
  },
  {
    id: 11,
    bpid: 1,
    mpid: 1,
    name: 'customer flow',
    icon: 'line-chart',
    router: '/chart/lineChart',
  },
  {
    id: 12,
    bpid: 1,
    mpid: 1,
    name: 'inStore flow',
    icon: 'line-chart',
    router: '/chart/lineChart',
  },
  {
    id: 13,
    bpid: 1,
    mpid: 1,
    name: 'inStore rate',
    icon: 'line-chart',
    router: '/chart/lineChart',
  },
  {
    id: 14,
    bpid: 1,
    mpid: 1,
    name: 'deepVisit rate',
    icon: 'line-chart',
    router: '/chart/lineChart',
  },
  {
    id: 15,
    bpid: 1,
    mpid: 1,
    name: 'outStore rate',
    icon: 'line-chart',
    router: '/chart/lineChart',
  },
  {
    id: 2,
    bpid: 1,
    name: 'Customer Activeness',
    icon: 'user',
    router: '/user',
  },
  {
    id: 3,
    bpid: 1,
    name: 'New and Old',
    icon: 'api',
    router: '/request',
  },
  {
    id: 4,
    bpid: 1,
    name: 'InStore Hours',
    icon: 'camera-o',
  },
  {
    id: 5,
    bpid: 1,
    name: 'Visit Cycle',
    icon: 'code-o',
  },

]
